Fixes to java files
percussion/percussioncms pull request #150
Opened 2021-05-27 03:35 UTC by malabikab

Java files

2021-05-27 15:49 UTC, natechadwick requested changes
@malabikab Please see the comments for areas that need changes before we can approve.

Thanks!
-n

2021-05-28 06:20 UTC, sonyDeswal reviewed
@Malabika Baguli There is one place where you have added == check in place of .equals()...please switch back that change... othewise changes are good to go...

2021-05-28 13:03 UTC, sonyDeswal submitted a review, later dismissed

2021-05-28 13:08 UTC, sonyDeswal approved these changes

2021-05-28 13:09 UTC, sonyDeswal approved these changes

2021-05-28 13:09 UTC, merged